### ISSUE TITLE
canvas.arrow not drawn correctly after changing penwidth size

### ISSUE THREAD

**Issue by eort** [smathot/OpenSesame#306]
The `canvas.arrow` function draws an arrow with a quite thin line. After trying to increase the thickness of that line (with `canvas.set_penwidth()`), the arrow changed its appearance in some weird way, so that it doesn't look like an arrow anymore. This happens both on Linux and Windows and under Legacy, psychopy and experiment backend (even though the resulting deformation looks a bit different each time). Also it happens regardless of the whether the penwidth is in- or decreased.

**Comment by smathot** [comment]
Hi Eduard,

You're right, that looks pretty crappy. The main problem is that an arrow is drawn as three separately lines, instead of as a polygon shape. Would you be interested in improving this? It would be a matter of rewriting `openexp._canvas.canvas.canvas.arrow()` so that it uses `openexp._canvas.canvas.canvas.polygon()`.

- https://github.com/smathot/OpenSesame/blob/master/openexp/_canvas/canvas.py#L599

While checking this I also noticed that the arrow-size field is not shown in the `sketchpad` GUI, which is a proper bug that I'll fix for 2.9.3.

Thanks!
Sebastiaan

**Comment by eort** [comment]
Hi Sebastiaan, 

Sure, I'll have a look on it, some time during the week. 

Eduard

**Comment by smathot** [comment]
Now being addressed in #330.
