### ISSUE TITLE
Resolution problem when running fullscreen on Microsoft Surface 3

### ISSUE THREAD

**Issue by Elaci0** [smathot/OpenSesame#328]
background: using a Microsoft Surface3 (1920x1200) resolution
Running opensesamerun.exe with its GUI works fine and the experiment can go to fullscreen
Running opensesamerun.exe   with the  "-f"  option  within a batch file (.bat)  does not work in the same way and the resolution goes down to 1200x800

**Comment by smathot** [comment]
Hi,

Thanks for your feedback. Could you provide some more details? It's a bit unclear to me what exactly happens.

- With which backend(s) does this problem occur?
- What is the resolution specified in the experiment?
- What exactly is the behavior when you run the experiment in fullscreen through the GUI?
- What exactly is the behavior when you run the experiment in fullscreen through opensesamerun?

Cheers,
Sebastiaan

**Comment by Elaci0** [comment]
Thanks for your help!
I tried all the backends available (except for Android) and with all the backend settings as suggested into some post in the forum.
the Microsoft Surface runs at 1920x 1280  and my resolution is set for that size.
running the experiment from the Opensesame's GUI  in full screen  doest not work and put the screen at lower resolution, i guess 1200x800, cropping out all the rest of the screen.SO my sketchpads are not displayed correctly. 
running the experiment from Opensesame's GUI  but in a windowed mode, simply "enlarge" the window like the double and I have to scroll it to view the rest of the screen.
running the experiment from  Opensesamerun.exe 's GUI, setting the filename and the "fullscreen" option, works fine and the experiment is correctly displayed.
running the experiment from  Opensesamerun.exe  but using a batch  doesn't work too and the screeen is displayed like running from Opensesame's GUI

I need the batch mode because I wanted run the experiment automatically and without user's interaction

again, thanks!

**Comment by smathot** [comment]
This is a weird issue, but I'm afraid we cannot do too much about it for the moment, because no-one in the team has a Microsoft Surface (as far as I know). So I'll leave the issue open so I don't forget.

In the meanwhile, if you have any more information, or if you experience the same problem on a different computer, please let me know!

**Comment by Elaci0** [comment]
I can run whatever test you need.
I have no direct experience with programming in python but I am able to debug if you could tell me where to take a look.

thanks!

**Comment by Elaci0** [comment]
Little Update:
after running some test with 'opensesamerun' from the sources and using a debugger I have the feeling that the QT dialog box influence somehow the rest of the script. Is that possible?
I modified the 'opensesamerun' script to always popup even if all the required parameters are passed from a batch and the experiment is shown with the correct resolution.
Also I believe the resolution is always correct it is like if there was a "zoom" and the screen is painted starting from 'outside' the device. Also, strangely, in the taskbar, the preview icon of the "pygame window" shows a screen with the correct size.

**Comment by smathot** [comment]
Thanks for digging into this!

> after running some test with 'opensesamerun' from the sources and using a debugger I have the feeling that the QT dialog box influence somehow the rest of the script. Is that possible?

To paraphrase Sherlock Holmes, *when you have eliminated the impossible, whatever remains, however improbable, must be the truth*. So yes, this seems to be what's going on.

> I modified the 'opensesamerun' script to always popup even if all the required parameters are passed from a batch and the experiment is shown with the correct resolution.

So if I understand correctly, briefly loading PyQt4 *prevents* the problem from occurring, right? So PyQt4 is the solution, rather than the problem.

One thing that comes to mind is that Windows scales applications to make sure that they are shown correctly on the high definition screen of the Surface. And that this scaling goes wrong for some reason, but only if the runtime is launched directly. Is there an option somewhere, hidden in the Windows settings, that allows you to specify this kind of thing? An option to indicate whether applications should be scaled, or something like that. I'm not familiar with Windows 8, so I don't what exactly to look for.

**Comment by Elaci0** [comment]
what a shame..
but honestly I would never have thought about that!
going to <b>Control Panel--> display --> "let me choose ONE scaling level for all my displays"  (with Larger 125% -default) </b>   setting  seems did the trick.
I can run opensesamerun.exe  from a batch with the full resolution (1920x1200) now!
..and of course also from inside  Opensesame's GUI I can run a fullscreen experiment
I wasted one day debugging but you save another one avoid me to recompile!
thanks!

**Comment by smathot** [comment]
Ok, I'll close this one then, because it's not directly OpenSesame related. But it's very good that we got to the bottom of it, because other people are likely to run into it as well!
