### ISSUE TITLE
Disabled combobox is re-enabled after switching items

### ISSUE THREAD

**Issue by JdenHartog** [smathot/OpenSesame#347]
Using (for example) the pygaze_drift_correct plug-in in OpenSesame 2.9.6 on Windows 7 x64:
The *Target color* and *Target style* both get disabled (grayed out) after unchecking *Show display with drift-correction target* as they should. But after switching to another item in the Overview and switching back to the pygaze_drift_correct item; the *Target color* (type line_edit) is still disabled but the *Target style* (type combobox) is re-enabled! I discovered this with a plug-in I'm, working on myself using a type SpinBox which appears to have the same problem.

![untitled](https://cloud.githubusercontent.com/assets/8225621/8826636/3cccbc04-3088-11e5-8a14-5961df0dec66.png)

**Comment by smathot** [comment]
Hi Jarik,

Thanks, as always.

I think I see what you mean, although on Linux I get slightly different behavior (maybe due to different focus rules). I'll first take a look at it to see if this is indeed a general problem with combobox items, or whether its PyGaze-specific. (In the last case, we should move this issue to the PyGaze repository.)

Cheers,  
Sebastiaan

**Comment by JdenHartog** [comment]
Hi Sebastiaan,

The same problem occurs when I’m, using the auto_example you refer to on http://osdoc.cogsci.nl/plug-ins/create-plug-in/
When changing the element  label: "Enter text" (that is enabled/disabled by the label: "Example checkbox") from type: "line_edit" to type: "combobox" (and adding options).
So I don’t think it’s a PyGaze problem.

I also tested a bit more with the auto_example plug-in:
The problem also appears with:
type: "spinbox"

The problem does NOT appear with:
type: "filepool"
type: "color_edit"
type: "editor"


Cheers,
Jarik

**Comment by smathot** [comment]
I took a quick look at it, and it is a problem with the PyGaze plug-in. If other plug-ins have the same problem (which is likely) then that's because it's a tricky thing to get right. The basic problem is that the GUI is updated when a change is applied, but not, or not properly, when it is shown. To do that, the plug-in needs to override both `apply_edit_changes` (which it already does) and `edit_widget` (which it doesn't).

So I'll close this here. But would you mind opening it again on the PyGaze repository?

- https://github.com/esdalmaijer/PyGaze

**Comment by JdenHartog** [comment]
To confirm: when adding the <code>edit_widget</code> override (borrowed from your boks plug-in), the type: "combobox" and type: "spinbox" in the auto_example plug-in stay in sync with the checkbox when toggling between items. 

I'll open it on the PyGaze repository. Thanks!
