### ISSUE TITLE
Crashing loops when running fullscreen, working fine in windowed mode

### ISSUE THREAD

**Issue by pinusm** [smathot/OpenSesame#349]
http://forum.cogsci.nl/index.php?p=/discussion/1247/open-qualtrics-survey-integration#Item_8

**Comment by pinusm** [comment]
possibly related?
https://github.com/smathot/OpenSesame/issues/53

**Comment by smathot** [comment]
Hi,

Aside from the fact that posting two links and two words is not the way to file an informative bug report (!), I looked at the forum post, and I don't see how this indicates a bug in OpenSesame. It looks like you've written a custom script to call an external program, and use another external program to switch focus between applications. I understand that it's annoying if it doesn't work as expected, but what makes you think the problem is in OpenSesame?

Cheers,
Sebastiaan
