### ISSUE TITLE
clock and keyboard refer to a different zero point in psychopy 

### ISSUE THREAD

**Issue by eort** [smathot/OpenSesame#381]
When a key was pressed using `keyboard.get_key(timeout)`, the returned timestamp seems to have a different reference point than when `clock.time()` is called. If no key is pressed, that is a timeout occurred, the timestamps do match. In a simple example, like the one below, `clock.time()` and `keyboard.get_key()` in case of a timeout, return a value in the thousands, whereas in case of a key press `keyboard.get_key()` returns a value in the region of 1e12. This happens only with psychopy as backend, not for legacy or expyriment. 

~~~ .python
kb = keyboard()
starttime = clock.time()
key,endtime = kb.get_key(timeout=3000)
print starttime,endtime,endtime-starttime
~~~

**Comment by smathot** [comment]
Hi Eduard,

As always, thanks for spotting this one. It seems to be due to the version of PsychoPy. Using Ubuntu 15.10, PsychoPy 1.82.02, this doesn't happen. Using Ubuntu 14.04, PsychoPy 1.79.01, it does. You probably use Ubuntu 14.04, right?

I'll take a look at it. I don't think it's high priority, because not many people are affected. But it would be better if it's fixed of course.

Cheers!  
Sebastiaan

**Comment by eort** [comment]
Hi Sebastiaan,

Yep, 14.04 it is. 

Good to hear. Then I probably can run the experiment in the lab and don't have to wait for the fix. 

Thanks for looking into this. 

Eduard
