### ISSUE TITLE
[Win32] "sound" value for duration in sampler ignored on first version of loop

### ISSUE THREAD

**Issue by jkordani** [smathot/OpenSesame#404]
Notice in the practicesounds sampler that the duration field is set to "sound" which is supposed to instruct the framework to wait until the sound file has played in it's entirety before progressing.  On every backend other than expyriment, the behavior is such that the first run of the loop, the "sound" parameter results in the duration becoming effectively 0, then correct behavior for subsequent runs.

I am attempting to build trunk on win32/64 and could use some pointers in order to dig into this, but for now I believe the attached osexp should have everything necessary to reproduce the issue.

I'm including @Jnaveblodgett so she can more closely track status.

[josh.zip](https://github.com/smathot/OpenSesame/files/174793/josh.zip)

**Comment by smathot** [comment]
Hi,

Thanks for pointing this out. This is a known issue (#401), which has already been fixed in the development snapshot. As a matter of fact, we intend to push out a maintenance release (3.0.7) including this fix *today*!

So I'm closing this as a duplicate, but, in any case, thanks for your effort and helping to make OpenSesame better.

Cheers,
Sebastiaan

**Comment by jkordani** [comment]
I apologize for not digging deeper into the issue tracker!  Thanks a lot!
