### ISSUE TITLE
proxy setting

### ISSUE THREAD

**Issue by Christianhigton** [smathot/OpenSesame#420]
Would it be possible to build proxy setting menu into  opensesame  so opensesame would be able to access OSF through proxy at university.

Thanks 

Chris

**Comment by smathot** [comment]
Hi Chris,

I think that this is best done by setting a system-wide proxy (@dschreij ?). But, in any case, please repost this issue in the `QOpenScienceFramework` repository, because that's where the OSF integration is maintained:

- https://github.com/dschreij/QOpenScienceFramework

Cheers and thanks for your feedback!
Sebastiaan

**Comment by dschreij** [comment]
Hi Chris,

Let's continue this discussion on the issue tracker of QOpenScienceFramework as @smathot suggested. For now, I did a quick search and saw that Qt (the library behind QOpenScienceFramework) offers a [QNetworkProxy](http://doc.qt.io/qt-5/qnetworkproxy.html) class that handles proxy configs, so I certainly think it is possible; I only don't know in what timespan I will be able to implement this. I will have to dive into this first to determine how much work it is. For now, it is indeed best to set-up a system-wide proxy if you want it to work. 
Thanks for bringing this up at least. It seems like a valuable addition to me to make this configurable in QOpenScienceFramework as I know a lot of university networks are behind proxies.
