### ISSUE TITLE
Data directory hard-coded

### ISSUE THREAD

**Issue by toddrme2178** [smathot/OpenSesame#421]
opensesame hard-codes "/usr/share/opensesame" as the directory for data files, both during the installation and in various python files in the package.  This make it impossible to, for example, install opensuse using the "--user" installation mode, change the package directories to conform to Linux distro rules, or install Python 2.x and Python 3.x versions side-by-side without there being file conflicts.

It would be very helpful if this used the paths specified during the installation rather than a hard-coded path.  Or better yet, install them in the Python package directory (at least as an option).

**Comment by smathot** [comment]
Hi,

This was indeed a limitation in OpenSesame 3.0 and earlier, but you'll find that it is already improved in 3.1 (in the `james` branch). Due to the almost infinite ways in which Python packages can be installed, there are probably still problems, so let me know if you encounter those (using 3.1). For now, I'll close this issue though.

Cheers!
Sebastiaan
