### ISSUE TITLE
Psycho back-end can't find resource 'sans.ttf'

### ISSUE THREAD

**Issue by JdenHartog** [smathot/OpenSesame#422]
Testing on a clean 64 bit Win 7 system I was able to reproduce the 'sans.ttf bug'.

After installing *opensesame_3.0.7-py2.7-win32-3.exe* and *vlc-2.2.3-win64.exe* the default template gives the following error when using the **psycho** back-end:

> item-stack: ``
exception message: The resource 'sans.ttf' could not be found in libopensesame.experiment.resource()
time: Tue May 24 08:56:55 2016
exception type: Exception
Traceback (also in debug window)

>  File "dist\libqtopensesame\misc\process.py", line 140, in run
  File "dist\libopensesame\experiment.py", line 386, in run
  File "dist\libopensesame\experiment.py", line 730, in init_display
  File "dist\openexp\canvas.py", line 65, in init_display
  File "dist\openexp\_canvas\psycho.py", line 370, in init_display
  File "dist\libopensesame\experiment.py", line 512, in resource
> Exception: The resource 'sans.ttf' could not be found in libopensesame.experiment.resource()

It is gone after either uninstalling *vlc-2.2.3-win***64***.exe* or installing *vlc-2.2.3-win***32***.exe* alongside.

I was able to track the error up to *"dist\openexp\_canvas\psycho.py", line 370, in init_display* where a *os.getcwd()* suddenly returns: *C:\Program Files\VideoLAN\VLC*

Another workaround is posted [here](http://www.cogsci.nl/forum/index.php?p=/discussion/1859/solution-of-the-resource-sans-ttf-could-not-be-found-in-libopensesame-experiment-resource-error)

Hope this helps. Best,
Jarik

**Comment by smathot** [comment]
Hi Jarik,

I see--thanks for the detective work. This appears to be due to bad behavior of both OpenSesame and the VLC Python bindings. Both try to change the working directory to their own directory, and when VLC does that, OpenSesame suddenly cannot find its own resources anymore.

I'm not sure how to best deal with this. In OpenSesame 3.1, the resources are located differently, so the problem might go away automatically. I'll leave it open as `unverified` for now, until we know for sure that it's resolved.

Cheers!
Sebastiaan

**Comment by JdenHartog** [comment]
Hi Sebastiaan,

Just tested with opensesame_3.1.1-py2.7-win32-1.exe and the problem is indeed gone! :+1:

I'll close this.

Cheers,
Jarik
