### ISSUE TITLE
Cycles from loop item are not imported from .opensesame file in OS 3.1.x

### ISSUE THREAD

**Issue by JdenHartog** [smathot/OpenSesame#450]
When opening an old .opensesame file in an OpenSesame 3.1.x version (like *opensesame_3.1.2-py2.7-win32-1.exe* for example) the number of *cycles* is not imported from the file. The attached file has 2 cycles repeated 3 times. When opening the experiment in either OS2.9.7 or OS3.0.7 both the number of *cycle*s and *repeat* are correct. But when opening in OS3.1.2 the number of *cycles* if always **1**. I guess this is because of the redesigned loop in OS 3.1 because OS3.0.7 does not have this problem.

[loop2x3.opensesame.txt](https://github.com/smathot/OpenSesame/files/461483/loop2x3.opensesame.txt) (remove the '.txt')

Best,
Jarik

**Comment by smathot** [comment]
Hi Jarik,

Thanks! The problem is that, before 3.1, the number of cycles was specified either by the `cycles` variable, or by the size of the loop table. Currently, only the size of the loop table is used, that is, it's no longer possible to have an empty loop table. This is more intuitive, I think, but for backwards compatibility the `cycles` should still be checked.

Cheers!
Sebastiaan

**Comment by JdenHartog** [comment]
Hi Sebastiaan,

You're welcome! I think it is more intuitive now as well.
I appreciate your informative and educational answer(s) 

Best,
Jarik
