### ISSUE TITLE
Proposal: Use context manager for easy canvas preparation

### ISSUE THREAD

**Issue by smathot** [smathot/OpenSesame#494]
# The problem

With the `xpyriment` backend, drawing many elements to a `canvas` is slow if `auto_prepare` is not set to `False`. So you need to do:

~~~ python
c = canvas(auto_prepare=False)
# Draw many stimuli
c.prepare()
# Later ...
c.show()
~~~

This is necessary, because the `canvas` needs to be prepared in order to be shown without delay. But it's not very elegant, and many users aren't aware of it.

# A solution

I propose the following syntax:

~~~ python
with canvas() as c:
	# Draw many stimuli
	pass
# Later ...
c.show()
~~~

Here, `auto_prepare` is set to `False` when the context is entered (i.e. inside the `with` block), and `canvas.prepare()` is automatically called when the context is exited (i.e. after the `with` block).

The following should also work:

~~~ python
c = canvas()
with c:
	# Draw many stimuli
	pass
# Later ...
c.show()
~~~

@dschreij @fladd @eort @Klemtonius Thoughts?

**Comment by dschreij** [comment]
Seems like a good solution, although I like the classic way without 'with' better. It pushes people into a certain style of programming, in the sense that they have to perform all drawing operations close together (or rather, I foresee massive with-blocks maybe spanning the entire script section in a lot of people's code).
Is this syntax only meant to cope with the exceptional situation of expyriment or do you also plan to make it standard practice for the other backends??

**Comment by smathot** [comment]
> Seems like a good solution, although I like the classic way without 'with' better.

Then it's actually *not* a good solution, is it? ;-)

> I foresee massive with-blocks maybe spanning the entire script section in a lot of people's code

That's true. In other words, it might lead to ugly code. 

> Is this syntax only meant to cope with the exceptional situation of expyriment or do you also plan to make it standard practice for the other backends??

Ideally, we would recommend the same code regardless of which backend is used. In other words, the `with` statement would only be useful for *xpyriment*, but we would nevertheless use it everywhere. The idea is that users shouldn't worry about the technical details of the backend, which right now they kind of have to (or accept ver slow performance with *xpyriment*).

So this `with` statement is intended to:

- allow for `canvas` objects to be preprared once all drawing operations are completed, without the user explicitly having to worry about this; and
- be intuitive, so that there is no cost in using it even if it's not necessary.

But there may be better ways to achieve these two goals, that's why I'm putting it here as a proposal.

**Comment by dschreij** [comment]
It's a good solution to solve the expyriment issue, but I'd be less of an advocate to make this standard practice of interacting with the canvas. I'm also wondering what happens if people create 2 consecutive with-blocks to interact with the canvas. Can a canvas still be edited after prepare has been called? (I assume so, but just to be sure) 

My two cents: I think it's better to get it into people's system to call canvas.prepare()  'manually' after they have finished their drawing operations by teaching this in the tutorials. This call of course won't do much with legacy or psychopy, but may be presented as good practice in general. We can then emphasize that if people experience slow behavior in expyriment, they have probably forgotten to call the prepare function.
